query Drivers{
  driver{
    allDrivers{
      id
      name
      phone
    }
  }
}

query MyQuery($id: Int!) {
  driver {
    driver(id: $id) {
      id
      name
      phone
    }
  }
}

