import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "@/providers/AppProvider";

import { Geo } from "next/font/google";

const geo = Geo({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "SDS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geo.className}>
      <body>
        <Providers>
          {children}
          <Toaster position="top-right" closeButton={true} />
        </Providers>
      </body>
    </html>
  );
}